<?php

/**
 * @file
 * Contains drupal_console_queue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_console_queue_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_console_queue module.
    case 'help.page.drupal_console_queue':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example module with drupal console Queue Worker generator') . '</p>';
      return $output;

    default:
  }
}
